#!/bin/bash

source ~/.profile

export ANDROID_HOME=/Users/bpascazio/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
export JAVA_HOME="/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home"

#alias ll='ls -la'
alias pr='cd ~/code/personal'
alias ce='cd "~/Library/MobileDevice/Provisioning Profiles"'
alias co='cd ~/code'
alias code='cd ~/code'
alias tn='cd ~/code/tech-notes'
alias ios='cd ~/code/client-ios'
alias and='cd ~/code/client-android'
alias gs='git status'
alias gr='git remote -v'
alias gb='git branch'
alias gp='git pull'
alias gl='git log'
alias gt='./gradlew tasks'
alias sf='swiftformat'
alias gd='git difftool -d -t opendiff'
alias pro='cd ~/Library/MobileDevice/Provisioning\ Profiles'

source ~/.git-completion.bash
source ~/.git-prompt.sh

MAGENTA="\[\033[0;35m\]"
YELLOW="\[\033[0;33m\]"
BLUE="\[\033[34m\]"
LIGHT_GRAY="\[\033[0;37m\]"
CYAN="\[\033[0;36m\]"
GREEN="\[\033[0;32m\]"
GIT_PS1_SHOWDIRTYSTATE=true
export LS_OPTIONS='--color=auto'
export CLICOLOR='Yes'
export LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD

export PS1=$LIGHT_GRAY"\u@\h"'$(
    if [[ $(__git_ps1) =~ \*\)$ ]]
    # a file has been modified but not added
    then echo "'$YELLOW'"$(__git_ps1 " (%s)")
    elif [[ $(__git_ps1) =~ \+\)$ ]]
    # a file has been added, but not commited
    then echo "'$MAGENTA'"$(__git_ps1 " (%s)")
    # the state is clean, changes are commited
    else echo "'$CYAN'"$(__git_ps1 " (%s)")
    fi)'$BLUE" \w"$GREEN": "

alias ll='ls -lah'
alias gg='git status -s'
alias gr='git log --graph --oneline --decorate'

#if [ -f ~/.bashrc ]; then
#   source ~/.bashrc
#fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

export PATH="$HOME/.fastlane/bin:$PATH"

